Feature/repair footer
odalviarez/scaneaMe pull request #108
Opened 2022-12-05 18:26 UTC by ekisler

2022-12-05 18:28 UTC, gzucca requested changes

2022-12-05 18:28 UTC, gzucca commented on client/src/components/footer/Footer.module.css
> +ul {
sigue el tag global. Ponele un nombre como ".nombreClassname ul" así no modifica todo el cliente

2022-12-05 18:41 UTC, ekisler commented on client/src/components/footer/Footer.module.css
> +ul {
Corregido!

2022-12-05 20:35 UTC, ekisler commented on client/src/components/footer/Footer.module.css
> +ul {
corregido parte 2

2022-12-06 13:59 UTC, gzucca approved these changes

2022-12-06 13:59 UTC, gzucca approved these changes

2022-12-06 14:00 UTC, merged